/// Sizes of immediate operands
#[derive(Debug)]
pub enum Imm {
    /// Constant size
    Constant(usize),

    /// Changes based on operand size prefix
    OpSize,

    /// Changes based on address size prefix
    AddrSize
}

/// Types of opcodes
#[derive(Debug)]
pub enum Opcode {
    /// Undefined opcode
    Invalid,

    /// Valid instruction
    Inst {
        has_modrm: bool,
        immediate: Imm,
    },
}

/// One-byte opcodes
pub const OPCODE_TABLE: [Opcode; 256] = [
    /* 0x00 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x01 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x02 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x03 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x04 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x05 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x06 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x07 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x08 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x09 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x0a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x0b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x0c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x0d */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x0e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x0f */  Opcode::Invalid,
    /* 0x10 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x11 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x12 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x13 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x14 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x15 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x16 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x17 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x18 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x19 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x1d */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x1e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x1f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x20 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x21 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x22 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x23 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x24 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x25 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x26 */  Opcode::Invalid,
    /* 0x27 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x28 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x29 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x2d */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x2e */  Opcode::Invalid,
    /* 0x2f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x30 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x31 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x32 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x33 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x34 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x35 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x36 */  Opcode::Invalid,
    /* 0x37 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x38 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x39 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x3a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x3b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x3c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x3d */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x3e */  Opcode::Invalid,
    /* 0x3f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x40 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x41 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x42 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x43 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x44 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x45 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x46 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x47 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x48 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x49 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4a */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4b */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4d */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x4f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x50 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x51 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x52 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x53 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x54 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x55 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x56 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x57 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x58 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x59 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5a */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5b */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5d */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x5f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x60 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x61 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x62 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x63 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x64 */  Opcode::Invalid,
    /* 0x65 */  Opcode::Invalid,
    /* 0x66 */  Opcode::Invalid,
    /* 0x67 */  Opcode::Invalid,
    /* 0x68 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0x69 */  Opcode::Inst { has_modrm: true, immediate: Imm::OpSize },
    /* 0x6a */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0x6b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0x6c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x6d */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x6e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x6f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x70 */  Opcode::Invalid,
    /* 0x71 */  Opcode::Invalid,
    /* 0x72 */  Opcode::Invalid,
    /* 0x73 */  Opcode::Invalid,
    /* 0x74 */  Opcode::Invalid,
    /* 0x75 */  Opcode::Invalid,
    /* 0x76 */  Opcode::Invalid,
    /* 0x77 */  Opcode::Invalid,
    /* 0x78 */  Opcode::Invalid,
    /* 0x79 */  Opcode::Invalid,
    /* 0x7a */  Opcode::Invalid,
    /* 0x7b */  Opcode::Invalid,
    /* 0x7c */  Opcode::Invalid,
    /* 0x7d */  Opcode::Invalid,
    /* 0x7e */  Opcode::Invalid,
    /* 0x7f */  Opcode::Invalid,
    /* 0x80 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0x81 */  Opcode::Inst { has_modrm: true, immediate: Imm::OpSize },
    /* 0x82 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0x83 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0x84 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x85 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x86 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x87 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x88 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x89 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8c */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8d */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x8f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x90 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x91 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x92 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x93 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x94 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x95 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x96 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x97 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x98 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x99 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x9a */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(4) },
    /* 0x9b */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x9c */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x9d */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x9e */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x9f */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa0 */  Opcode::Inst { has_modrm: false, immediate: Imm::AddrSize },
    /* 0xa1 */  Opcode::Inst { has_modrm: false, immediate: Imm::AddrSize },
    /* 0xa2 */  Opcode::Inst { has_modrm: false, immediate: Imm::AddrSize },
    /* 0xa3 */  Opcode::Inst { has_modrm: false, immediate: Imm::AddrSize },
    /* 0xa4 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa5 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa6 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa7 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa8 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xa9 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xaa */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xab */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xac */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xad */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xae */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xaf */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xb0 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb1 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb2 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb3 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb4 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb5 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb6 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb7 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xb8 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xb9 */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xba */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xbb */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xbc */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xbd */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xbe */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xbf */  Opcode::Inst { has_modrm: false, immediate: Imm::OpSize },
    /* 0xc0 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xc1 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xc2 */  Opcode::Invalid,
    /* 0xc3 */  Opcode::Invalid,
    /* 0xc4 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xc5 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xc6 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xc7 */  Opcode::Inst { has_modrm: true, immediate: Imm::OpSize },
    /* 0xc8 */  Opcode::Invalid,
    /* 0xc9 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xca */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(2) },
    /* 0xcb */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xcc */  Opcode::Invalid,
    /* 0xcd */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xce */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xcf */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xd0 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd1 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd2 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd3 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd4 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xd5 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xd6 */  Opcode::Invalid,
    /* 0xd7 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xd8 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd9 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xda */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdb */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdc */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdd */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xde */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdf */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe0 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe1 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe2 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe3 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe4 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe5 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe6 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe7 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(1) },
    /* 0xe8 */  Opcode::Invalid,
    /* 0xe9 */  Opcode::Invalid,
    /* 0xea */  Opcode::Invalid,
    /* 0xeb */  Opcode::Invalid,
    /* 0xec */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xed */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xee */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xef */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xf0 */  Opcode::Invalid,
    /* 0xf1 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xf2 */  Opcode::Invalid,
    /* 0xf3 */  Opcode::Invalid,
    /* 0xf4 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xf5 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xf6 */  Opcode::Invalid,
    /* 0xf7 */  Opcode::Invalid,
    /* 0xf8 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xf9 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xfa */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xfb */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xfc */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xfd */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xfe */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xff */  Opcode::Invalid
];

/// Two-byte opcodes
pub const OPCODE_TABLE_0F: [Opcode; 256] = [
    /* 0x00 */  Opcode::Invalid,
    /* 0x01 */  Opcode::Invalid,
    /* 0x02 */  Opcode::Invalid,
    /* 0x03 */  Opcode::Invalid,
    /* 0x04 */  Opcode::Invalid,
    /* 0x05 */  Opcode::Invalid,
    /* 0x06 */  Opcode::Invalid,
    /* 0x07 */  Opcode::Invalid,
    /* 0x08 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x09 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x0a */  Opcode::Invalid,
    /* 0x0b */  Opcode::Invalid,
    /* 0x0c */  Opcode::Invalid,
    /* 0x0d */  Opcode::Invalid,
    /* 0x0e */  Opcode::Invalid,
    /* 0x0f */  Opcode::Invalid,
    /* 0x10 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x11 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x12 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x13 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x14 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x15 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x16 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x17 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x18 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x19 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1c */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1d */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x1f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x20 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x21 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x22 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x23 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x24 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x25 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x26 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x27 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x28 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x29 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2c */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2d */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x2f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x30 */  Opcode::Invalid,
    /* 0x31 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x32 */  Opcode::Invalid,
    /* 0x33 */  Opcode::Invalid,
    /* 0x34 */  Opcode::Invalid,
    /* 0x35 */  Opcode::Invalid,
    /* 0x36 */  Opcode::Invalid,
    /* 0x37 */  Opcode::Invalid,
    /* 0x38 */  Opcode::Invalid,
    /* 0x39 */  Opcode::Invalid,
    /* 0x3a */  Opcode::Invalid,
    /* 0x3b */  Opcode::Invalid,
    /* 0x3c */  Opcode::Invalid,
    /* 0x3d */  Opcode::Invalid,
    /* 0x3e */  Opcode::Invalid,
    /* 0x3f */  Opcode::Invalid,
    /* 0x40 */  Opcode::Invalid,
    /* 0x41 */  Opcode::Invalid,
    /* 0x42 */  Opcode::Invalid,
    /* 0x43 */  Opcode::Invalid,
    /* 0x44 */  Opcode::Invalid,
    /* 0x45 */  Opcode::Invalid,
    /* 0x46 */  Opcode::Invalid,
    /* 0x47 */  Opcode::Invalid,
    /* 0x48 */  Opcode::Invalid,
    /* 0x49 */  Opcode::Invalid,
    /* 0x4a */  Opcode::Invalid,
    /* 0x4b */  Opcode::Invalid,
    /* 0x4c */  Opcode::Invalid,
    /* 0x4d */  Opcode::Invalid,
    /* 0x4e */  Opcode::Invalid,
    /* 0x4f */  Opcode::Invalid,
    /* 0x50 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x51 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x52 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x53 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x54 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x55 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x56 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x57 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x58 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x59 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x5a */  Opcode::Invalid,
    /* 0x5b */  Opcode::Invalid,
    /* 0x5c */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x5d */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x5e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x5f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x60 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x61 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x62 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x63 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x64 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x65 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x66 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x67 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x68 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x69 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x6a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x6b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x6c */  Opcode::Invalid,
    /* 0x6d */  Opcode::Invalid,
    /* 0x6e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x6f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x70 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0x71 */  Opcode::Invalid,
    /* 0x72 */  Opcode::Invalid,
    /* 0x73 */  Opcode::Invalid,
    /* 0x74 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x75 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x76 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x77 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0x78 */  Opcode::Invalid,
    /* 0x79 */  Opcode::Invalid,
    /* 0x7a */  Opcode::Invalid,
    /* 0x7b */  Opcode::Invalid,
    /* 0x7c */  Opcode::Invalid,
    /* 0x7d */  Opcode::Invalid,
    /* 0x7e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x7f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x80 */  Opcode::Invalid,
    /* 0x81 */  Opcode::Invalid,
    /* 0x82 */  Opcode::Invalid,
    /* 0x83 */  Opcode::Invalid,
    /* 0x84 */  Opcode::Invalid,
    /* 0x85 */  Opcode::Invalid,
    /* 0x86 */  Opcode::Invalid,
    /* 0x87 */  Opcode::Invalid,
    /* 0x88 */  Opcode::Invalid,
    /* 0x89 */  Opcode::Invalid,
    /* 0x8a */  Opcode::Invalid,
    /* 0x8b */  Opcode::Invalid,
    /* 0x8c */  Opcode::Invalid,
    /* 0x8d */  Opcode::Invalid,
    /* 0x8e */  Opcode::Invalid,
    /* 0x8f */  Opcode::Invalid,
    /* 0x90 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x91 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x92 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x93 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x94 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x95 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x96 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x97 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x98 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x99 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9a */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9b */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9c */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9d */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9e */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0x9f */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xa0 */  Opcode::Invalid,
    /* 0xa1 */  Opcode::Invalid,
    /* 0xa2 */  Opcode::Inst { has_modrm: false, immediate: Imm::Constant(0) },
    /* 0xa3 */  Opcode::Invalid,
    /* 0xa4 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xa5 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xa6 */  Opcode::Invalid,
    /* 0xa7 */  Opcode::Invalid,
    /* 0xa8 */  Opcode::Invalid,
    /* 0xa9 */  Opcode::Invalid,
    /* 0xaa */  Opcode::Invalid,
    /* 0xab */  Opcode::Invalid,
    /* 0xac */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xad */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xae */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xaf */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xb0 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xb1 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xb2 */  Opcode::Invalid,
    /* 0xb3 */  Opcode::Invalid,
    /* 0xb4 */  Opcode::Invalid,
    /* 0xb5 */  Opcode::Invalid,
    /* 0xb6 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xb7 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xb8 */  Opcode::Invalid,
    /* 0xb9 */  Opcode::Invalid,
    /* 0xba */  Opcode::Invalid,
    /* 0xbb */  Opcode::Invalid,
    /* 0xbc */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xbd */  Opcode::Invalid,
    /* 0xbe */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xbf */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xc0 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xc1 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xc2 */  Opcode::Invalid,
    /* 0xc3 */  Opcode::Invalid,
    /* 0xc4 */  Opcode::Invalid,
    /* 0xc5 */  Opcode::Invalid,
    /* 0xc6 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(1) },
    /* 0xc7 */  Opcode::Invalid,
    /* 0xc8 */  Opcode::Invalid,
    /* 0xc9 */  Opcode::Invalid,
    /* 0xca */  Opcode::Invalid,
    /* 0xcb */  Opcode::Invalid,
    /* 0xcc */  Opcode::Invalid,
    /* 0xcd */  Opcode::Invalid,
    /* 0xce */  Opcode::Invalid,
    /* 0xcf */  Opcode::Invalid,
    /* 0xd0 */  Opcode::Invalid,
    /* 0xd1 */  Opcode::Invalid,
    /* 0xd2 */  Opcode::Invalid,
    /* 0xd3 */  Opcode::Invalid,
    /* 0xd4 */  Opcode::Invalid,
    /* 0xd5 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd6 */  Opcode::Invalid,
    /* 0xd7 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd8 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xd9 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xda */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdb */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdc */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdd */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xde */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xdf */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe0 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe1 */  Opcode::Invalid,
    /* 0xe2 */  Opcode::Invalid,
    /* 0xe3 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe4 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe5 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe6 */  Opcode::Invalid,
    /* 0xe7 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe8 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xe9 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xea */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xeb */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xec */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xed */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xee */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xef */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xf0 */  Opcode::Invalid,
    /* 0xf1 */  Opcode::Invalid,
    /* 0xf2 */  Opcode::Invalid,
    /* 0xf3 */  Opcode::Invalid,
    /* 0xf4 */  Opcode::Invalid,
    /* 0xf5 */  Opcode::Invalid,
    /* 0xf6 */  Opcode::Invalid,
    /* 0xf7 */  Opcode::Invalid,
    /* 0xf8 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xf9 */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xfa */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xfb */  Opcode::Invalid,
    /* 0xfc */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xfd */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xfe */  Opcode::Inst { has_modrm: true, immediate: Imm::Constant(0) },
    /* 0xff */  Opcode::Invalid
];
